application: add-robots-website
version: 8
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#root
- url: /
  static_files: static_website/index.html
  upload: static_website/index.html

#serve our home page in case index.html is requested
- url: /index.html
  static_files: static_website/index.html
  upload: static_website/index.html

#specific html pages:
- url: /about.html
  static_files: static_website/about.html
  upload: static_website/about.html

- url: /devlog.html
  static_files: static_website/devlog.html
  upload: static_website/devlog.html

#all images and support file (css, fonts...): return file if found, 
#otherwise the default 404 page so it can be handled by sites that link
#directly to images.
- url: /(.*\.(js|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|json|xml))
  static_files: static_website/\1
  upload: static_website/(.*\.(js|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff|json|xml))  

#all other urls: return the 404 not found 
- url: /.*
  static_files: static_website/notfound.html 
  upload: static_website/notfound.html

libraries:
- name: webapp2
  version: "2.5.2"