site_name: AddRobots
site_description: 'Transmit'
site_author: 'Jeff Williams'
site_url: 'https://www.addrobots.com/transmit'

pages:
- Transmit: 'index.md'
- 2018:
  - Begin Transmit: '2018/begin.transmit.md'

theme:
  name: 'material'
  theme_dir: themes/material
  custom_dir: theme-overrides
  favicon: 'images/favicon/favicon.ico'
  logo: 'images/favicon/apple-icon-144x144.png'
  feature:
    tabs: true
    
extra:
  feature:
    tabs: true
  logo: 'images/profile.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/0x6a77'
    - type: 'envelope-square'
      link: 'http://eepurl.com/dl_CsD'

markdown_extensions:
  - tables
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
repo_url: https://github.com/AddRobots/addrobots_docs/
copyright: AddRobots News<br>Copyright &copy; 2018 <a href="https://github.com/0x6a77">Jeff Williams</a>

extra_css:
  - ./js/extra.css

extra_javascript:
#  - 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.js'
#  - 'https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.5.1/snap.svg-min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js'
#  - 'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-snap-min.js'
#  - 'js/sequence-diagram-rafael-min.js'
#  - 'js/sequence-diagram-snap-min.js'
#  - 'js/extra.js'

google_analytics:
  - 'UA-77221538-1'
  - 'auto'
